name: Manual Bot Host
on: workflow_dispatch

jobs:
  host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python & Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip xvfb
          pip install roblox requests

      - name: Generate Temporary SSH Key
        run: ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""

      - name: Start Interactive Screen
        uses: mxschmitt/action-tmate@v3
